CREATE TABLE TABLE_1( WORKING_ID INT(25) PRIMARY KEY,NAMES CHAR(1000));

INSERT INTO TABLE_1 VALUES(1, 'JAI'),(209, 'LAVANYA'),(354,'JAXA'); 

SELECT * FROM TABLE_1;

CREATE TABLE TABLE_2(Id INT PRIMARY KEY, first_NAME TEXT, last_NAME TEXT, AGE INT);

INSERT INTO TABLE_2 VALUES(10, 'JAHNAVI','THOTA ',24),(20, 'JANANI','CHIRAPU',21),(35,'BHANU','PRAKASH',35); 

SELECT * FROM TABLE_2;

CREATE TABLE TABLE_3(
JOB_ID INT NOT NULL,
GENDER TEXT,
SALARY INT,
PRIMARY KEY (JOB_ID),
FOREIGN KEY(SALARY)
REFERENCES TABLE_2 (SALARY));

SELECT * FROM TABLE_3;